language: r
sudo: false
cache: packages

before_script:
  - export NOT_CRAN=false
  - rm -rf vignettes

matrix:
  include:
  - r: release
  - r: devel

branches:
  except:
  - dev

notifications:
  email: false

after_success:
  - Rscript -e 'covr::codecov()'