---
title: "API Changes"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{API Changes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



## Summary of the API changes announced in 2021
 
In July of 2021 the Patentview API team announced upcoming API changes here https://patentsview.org/data-in-action/whats-new-patentsview-july-2021.  This page will explain the impact to the r package and any existing code.
 
The Patentsview API team has provided a Swagger UI page for the new version of the API at https://search.patentsview.org/swagger-ui/. It shows all the available endpoints and their responses.  Each field in the 200 response sections could be requested in the fields/f: parameter and each field is supposed to be queryable (usable in the query/q: parameter).  The Swagger UI page can be used to make requests, if you have an API key to enter in the authorization screen, more about the new API key below.  The Swagger UI definition at https://patentsview.historicip.com/swagger/openapi_v2.yml can be imported into Postman to give you a nicely loaded collection for the changed API. You'll just need to set a global variable PVIEW_KEY and set the authorization's value to {{PVIEW_KEY}} to your API key. (The patentsview's Swagger UI definition https://search.patentsview.org/static/openapi_v2.yml could be imported into Postman but it currently contains errors and does not contain a servers entry.  This was reported to the API team.)

## An API Key is required
Perhaps the most important change, without an API key your queries will be rejected.  Request an API key using this link: https://patentsview.org/apis/keyrequest  Once you have one, you'll need to set an environmental variable PATENTSVIEW_API_KEY to the value of your API key for the R package to use.

## Philosophical Changes
These changes are likely to break existing code.  Now there are more endpoints and each returns a smaller, more specific data structure pertinent to that endpoint. As an example, previously the inventor endpoint could return assignee information, it no longer does that.  The exception is the patents endpoint.  It now can return assignees_at_grant, inventors_at_grant, cpc_current along with patent specific fields. Note that now subsequent queries would have to be made to the USPC specific endpoints if you are looking for these fields.

Currently there are 16 endpoints, up from the original 7.  The urls changed slightly but the R package takes care of that for you.  

1. There are 8 totally new endpoints
   -  /api/v1/ipcs/  
   -  /api/v1/uspc_subclass/
   -  /api/v1/patent/attorneys
   -  /api/v1/patent/foreign_citations/
   -  /api/v1/patent/otherreference/  (not currently working)
   -  /api/v1/patent/patent/rel_app_texts/
   -  /api/v1/patent/us_application_citation/  
   -  /api/v1/patent/us_patent_citation/  
2. 5 of the original api's endpoints have singular names but lighter responses and fewer queryable fields as mentioned above.  
   -  /api/v1/assignee/  
   -  /api/v1/inventor/ 
   -  /api/v1/location/
   -  /api/v1/patent/  
   -  /api/v1/uspc_mainclass/
3. The original cpc endpoint has a new name and there are two new cpc endpoints
   -  /api/v1/cpc_class/
   -  /api/v1/cpc_subclass/
   -  /api/v1/cpc_group/
4. The nber_subcategory endpoint seem to be gone now.


## Data Reduction

Some fields seem to have gone away, raw inventor fields, coinventor fields, patent_firstnamed fields and patent_num_claims.  There's a link to a spreadsheet of the fields returned by endpoint at the bottom of https://patentsview.org/apis/purpose though the Swagger UI page should be more current.

## HATEOAS
Some of the returned fields are HATEOAS (Hypermedia as the Engine of Application State) links to retrieve more information about that field. Slight funky is the cpc_current's cpc_group, returned by the patents endpoint.  Here the slash in the cpc is turned into a colon.  This is a peculiarity of two of the new convience urls that shouldn't be noticable in the r package, unless you are trying to infer the uspc and cpc values from the returned urls, without actually calling back for this data.
There is something slightly funky with these fields.  They have an _id when in the q:/query and f:/fields parameters but they are returned without the _id.  Example: cpc_group_id is returned as the HATEOAS link cpc_group. 

Example link returned by the patents endpoint
```
 "cpc_current": {
     "cpc_group": "https://search.patentsview.org/api/v1/cpc_group/G01S7:4865/"  
  }
```
Note that going to that link in a browser will result in a 403 Unauthorized, as no API key is sent.

There is a new method in the R package to retrive data from the HATEOAS links, just pass the returned
link and the R package will retrieve the data for you.  

```r
library(patentsview)

pv_data <- retrieve_linked_data("https://search.patentsview.org/api/v1/cpc_group/G01S7:4865/")
pv_data
#> $data
#> #### A list with a single data frame on cpc_groups level:
#> 
#> List of 1
#>  $ cpc_groups:'data.frame':	100 obs. of  4 variables:
#>   ..$ cpc_class      : chr [1:100] "https://search.patentsview.org/api/v1/cpc"..
#>   ..$ cpc_subclass   : chr [1:100] "https://search.patentsview.org/api/v1/cpc"..
#>   ..$ cpc_group_id   : chr [1:100] "A01B1/00" ...
#>   ..$ cpc_group_title: chr [1:100] "Hand tools" ...
#> 
#> $query_results
#> #### Distinct entity counts across all downloadable pages of output:
#> 
#> total_hits = 242,232

if(pv_data$query_results$total_hits != 1){
   print("something is wrong with the API.  Response should match this:")
   query <- qry_funs$eq("cpc_group_id" = "G01S7/4865")
   search_pv(query, endpoint = "cpc_groups")
}
#> [1] "something is wrong with the API.  Response should match this:"
#> $data
#> #### A list with a single data frame on cpc_groups level:
#> 
#> List of 1
#>  $ cpc_groups:'data.frame':	1 obs. of  4 variables:
#>   ..$ cpc_class      : chr "https://search.patentsview.org/api/v1/cpc_class/G"..
#>   ..$ cpc_subclass   : chr "https://search.patentsview.org/api/v1/cpc_subclas"..
#>   ..$ cpc_group_id   : chr "G01S7/4865"
#>   ..$ cpc_group_title: chr "Details of systems according to groups G01S13/00,"..
#> 
#> $query_results
#> #### Distinct entity counts across all downloadable pages of output:
#> 
#> total_hits = 1
```

## Throttling
The API will now allow 45 requests per minute, making more requests will anger the API.  It will send back an error code with a header indicating how many seconds to wait before sending more queries.  The R package will take care of this for you.  It will sleep for the required number of seconds before resubmitting your query, seemlessly to your script.

## Alpha Fields

fieldsdf will show you the field types, names and endpoints in the new version of the API.  There are different operators for string and full text fields.

```r
library(knitr)
library(dplyr)

string_fields <-
   fieldsdf %>%
      filter(data_type == "string")  %>%
      select(endpoint, field, data_type) %>%
      arrange(`endpoint`, `field`)  
 
kable(string_fields,  row.names = FALSE, caption = 'String Fields')
```



Table: String Fields

|endpoint                        |field                                            |data_type |
|:-------------------------------|:------------------------------------------------|:---------|
|assignees                       |assignee_id                                      |string    |
|assignees                       |assignee_individual_name_first                   |string    |
|assignees                       |assignee_individual_name_last                    |string    |
|assignees                       |assignee_lastknown_city                          |string    |
|assignees                       |assignee_lastknown_country                       |string    |
|assignees                       |assignee_lastknown_location                      |string    |
|assignees                       |assignee_lastknown_state                         |string    |
|assignees                       |assignee_organization                            |string    |
|assignees                       |assignee_type                                    |string    |
|cpc_classes                     |cpc_class_id                                     |string    |
|cpc_classes                     |cpc_class_title                                  |string    |
|cpc_groups                      |cpc_class_id                                     |string    |
|cpc_groups                      |cpc_group_id                                     |string    |
|cpc_groups                      |cpc_group_title                                  |string    |
|cpc_groups                      |cpc_subclass_id                                  |string    |
|cpc_subclasses                  |cpc_class_id                                     |string    |
|cpc_subclasses                  |cpc_subclass_id                                  |string    |
|cpc_subclasses                  |cpc_subclass_title                               |string    |
|inventors                       |inventor_id                                      |string    |
|inventors                       |inventor_lastknown_city                          |string    |
|inventors                       |inventor_lastknown_country                       |string    |
|inventors                       |inventor_lastknown_location                      |string    |
|inventors                       |inventor_lastknown_state                         |string    |
|inventors                       |inventor_name_first                              |string    |
|inventors                       |inventor_name_last                               |string    |
|ipcs                            |ipc_class                                        |string    |
|ipcs                            |ipc_id                                           |string    |
|ipcs                            |ipc_section                                      |string    |
|ipcs                            |ipc_subclass                                     |string    |
|locations                       |location_country                                 |string    |
|locations                       |location_county                                  |string    |
|locations                       |location_county_fips                             |string    |
|locations                       |location_id                                      |string    |
|locations                       |location_name                                    |string    |
|locations                       |location_place_type                              |string    |
|locations                       |location_state                                   |string    |
|locations                       |location_state_fips                              |string    |
|patent/attorneys                |attorney_id                                      |string    |
|patent/attorneys                |attorney_name_first                              |string    |
|patent/attorneys                |attorney_name_last                               |string    |
|patent/attorneys                |attorney_organization                            |string    |
|patent/foreign_citations        |citation_category                                |string    |
|patent/foreign_citations        |citation_country                                 |string    |
|patent/foreign_citations        |citation_number                                  |string    |
|patent/foreign_citations        |patent_id                                        |string    |
|patent/otherreferences          |patent_id                                        |string    |
|patent/otherreferences          |reference_sequence                               |string    |
|patent/otherreferences          |reference_text                                   |string    |
|patent/rel_app_texts            |patent_id                                        |string    |
|patent/rel_app_texts            |related_text                                     |string    |
|patent/us_application_citations |citation_category                                |string    |
|patent/us_application_citations |citation_document_number                         |string    |
|patent/us_application_citations |citation_name                                    |string    |
|patent/us_application_citations |citation_wipo_kind                               |string    |
|patent/us_application_citations |patent_id                                        |string    |
|patent/us_patent_citations      |citation_category                                |string    |
|patent/us_patent_citations      |citation_name                                    |string    |
|patent/us_patent_citations      |citation_patent_id                               |string    |
|patent/us_patent_citations      |citation_wipo_kind                               |string    |
|patent/us_patent_citations      |patent_id                                        |string    |
|patents                         |applicants.applicant_designation                 |string    |
|patents                         |applicants.applicant_name_first                  |string    |
|patents                         |applicants.applicant_name_last                   |string    |
|patents                         |applicants.applicant_organization                |string    |
|patents                         |applicants.applicant_type                        |string    |
|patents                         |applicants.location_id                           |string    |
|patents                         |application.application_id                       |string    |
|patents                         |application.application_type                     |string    |
|patents                         |application.filing_type                          |string    |
|patents                         |application.series_code                          |string    |
|patents                         |assignees.assignee_city                          |string    |
|patents                         |assignees.assignee_country                       |string    |
|patents                         |assignees.assignee_id                            |string    |
|patents                         |assignees.assignee_individual_name_first         |string    |
|patents                         |assignees.assignee_individual_name_last          |string    |
|patents                         |assignees.assignee_location_id                   |string    |
|patents                         |assignees.assignee_organization                  |string    |
|patents                         |assignees.assignee_state                         |string    |
|patents                         |assignees.assignee_type                          |string    |
|patents                         |attorneys.attorney_id                            |string    |
|patents                         |attorneys.attorney_name_first                    |string    |
|patents                         |attorneys.attorney_name_last                     |string    |
|patents                         |attorneys.attorney_organization                  |string    |
|patents                         |botanic.latin_name                               |string    |
|patents                         |botanic.variety                                  |string    |
|patents                         |cpc_at_issue.cpc_class_id                        |string    |
|patents                         |cpc_at_issue.cpc_group_id                        |string    |
|patents                         |cpc_at_issue.cpc_section                         |string    |
|patents                         |cpc_at_issue.cpc_subclass_id                     |string    |
|patents                         |cpc_at_issue.cpc_type                            |string    |
|patents                         |cpc_current.cpc_class_id                         |string    |
|patents                         |cpc_current.cpc_group_id                         |string    |
|patents                         |cpc_current.cpc_section                          |string    |
|patents                         |cpc_current.cpc_subclass_id                      |string    |
|patents                         |cpc_current.cpc_type                             |string    |
|patents                         |examiners.art_group                              |string    |
|patents                         |examiners.examiner_first_name                    |string    |
|patents                         |examiners.examiner_id                            |string    |
|patents                         |examiners.examiner_last_name                     |string    |
|patents                         |examiners.examiner_role                          |string    |
|patents                         |foreign_priority.foreign_application_id          |string    |
|patents                         |foreign_priority.foreign_country_filed           |string    |
|patents                         |foreign_priority.priority_claim_kind             |string    |
|patents                         |gov_interest_contract_award_numbers.award_number |string    |
|patents                         |gov_interest_organizations.fedagency_name        |string    |
|patents                         |gov_interest_organizations.level_one             |string    |
|patents                         |gov_interest_organizations.level_three           |string    |
|patents                         |gov_interest_organizations.level_two             |string    |
|patents                         |gov_interest_statement                           |string    |
|patents                         |granted_pregrant_crosswalk.application_number    |string    |
|patents                         |inventors.inventor_city                          |string    |
|patents                         |inventors.inventor_country                       |string    |
|patents                         |inventors.inventor_id                            |string    |
|patents                         |inventors.inventor_location_id                   |string    |
|patents                         |inventors.inventor_name_first                    |string    |
|patents                         |inventors.inventor_name_last                     |string    |
|patents                         |inventors.inventor_state                         |string    |
|patents                         |ipcr.ipc_class                                   |string    |
|patents                         |ipcr.ipc_classification_data_source              |string    |
|patents                         |ipcr.ipc_classification_value                    |string    |
|patents                         |ipcr.ipc_id                                      |string    |
|patents                         |ipcr.ipc_main_group                              |string    |
|patents                         |ipcr.ipc_section                                 |string    |
|patents                         |ipcr.ipc_subclass                                |string    |
|patents                         |ipcr.ipc_subgroup                                |string    |
|patents                         |ipcr.ipc_symbol_position                         |string    |
|patents                         |patent_abstract                                  |string    |
|patents                         |patent_id                                        |string    |
|patents                         |patent_title                                     |string    |
|patents                         |patent_type                                      |string    |
|patents                         |pct_data.application_kind                        |string    |
|patents                         |pct_data.pct_doc_number                          |string    |
|patents                         |pct_data.pct_doc_type                            |string    |
|patents                         |us_related_documents.published_country           |string    |
|patents                         |us_related_documents.related_doc_kind            |string    |
|patents                         |us_related_documents.related_doc_number          |string    |
|patents                         |us_related_documents.related_doc_status          |string    |
|patents                         |us_related_documents.related_doc_type            |string    |
|patents                         |us_related_documents.wipo_kind                   |string    |
|patents                         |us_term_of_grant.term_disclaimer                 |string    |
|patents                         |us_term_of_grant.term_extension                  |string    |
|patents                         |us_term_of_grant.term_grant                      |string    |
|patents                         |uspc_at_issue.uspc_mainclass_id                  |string    |
|patents                         |uspc_at_issue.uspc_subclass_id                   |string    |
|patents                         |wipo.wipo_field_id                               |string    |
|patents                         |wipo_kind                                        |string    |
|uspc_mainclasses                |uspc_mainclass_id                                |string    |
|uspc_mainclasses                |uspc_mainclass_title                             |string    |
|uspc_subclasses                 |uspc_mainclass_id                                |string    |
|uspc_subclasses                 |uspc_subclass_id                                 |string    |
|uspc_subclasses                 |uspc_subclass_title                              |string    |
|wipo                            |field_title                                      |string    |
|wipo                            |sector_title                                     |string    |
|wipo                            |wipo_id                                          |string    |

```r

fulltext_fields <-
   fieldsdf %>%
      filter(data_type == "fulltext")  %>%
      select(endpoint, field, data_type) %>%
      arrange(endpoint, field)  
 
kable(fulltext_fields ,  row.names = FALSE, caption = 'Full Text Fields')
```



Table: Full Text Fields

|endpoint |field |data_type |
|:--------|:-----|:---------|

## Other Changes

* Some of the fields names changed.  assignee_last_name is now name_last in the assignees data structure.

* Some fields' types have changed, some strings in the original version of the API have become a full text field and some full text fields have becomes strings.  This means you'll need to use different methods
when including them in your query.  Example: assignee organization is renamed organization and is now a full text field, formerly it had been a string.

* The API's endpoints are now singular, instead of being plural.  Ex /patents is now /patent  The returned data structures are still plural, ex. patents.  The R package will keep using the plural endpoint names to match the returned data structures. When calling the API, the R package will request the singular endpoints. There would be a small chance that an existing script would work, once the now-required API key is set up.

* All fields are supposed to be queryable with the new version of the API.

* The subdomain of the API changed from https://api.patentsview.org/ to https://search.patentsview.org.  The R package takes care of this for you.

* Nested fields seem to need to be fully qualified in the f:parameter. Here are all the patents endpoint's fields:

```r
get_fields("patents")
#>   [1] "inventors.inventor_city"                                     
#>   [2] "patent_num_us_applications_cited"                            
#>   [3] "foreign_priority.foreign_country_filed"                      
#>   [4] "granted_pregrant_crosswalk.document_number"                  
#>   [5] "us_term_of_grant.term_grant"                                 
#>   [6] "us_term_of_grant.disclaimer_date"                            
#>   [7] "granted_pregrant_crosswalk.application_number"               
#>   [8] "assignees.assignee_country"                                  
#>   [9] "pct_data.pct_doc_number"                                     
#>  [10] "application.application_id"                                  
#>  [11] "cpc_at_issue.cpc_section"                                    
#>  [12] "us_related_documents.related_doc_number"                     
#>  [13] "ipcr.ipc_sequence"                                           
#>  [14] "uspc_at_issue.uspc_subclass_id"                              
#>  [15] "ipcr.ipc_subgroup"                                           
#>  [16] "application.filing_type"                                     
#>  [17] "inventors.inventor_state"                                    
#>  [18] "applicants.applicant_designation"                            
#>  [19] "examiners.examiner_role"                                     
#>  [20] "botanic.variety"                                             
#>  [21] "patent_processing_days"                                      
#>  [22] "assignees.assignee_individual_name_last"                     
#>  [23] "foreign_priority.priority_claim_kind"                        
#>  [24] "cpc_current.cpc_section"                                     
#>  [25] "patent_num_times_cited_by_us_patents"                        
#>  [26] "gov_interest_organizations.level_three"                      
#>  [27] "attorneys.attorney_organization"                             
#>  [28] "pct_data.pct_102_date"                                       
#>  [29] "ipcr.ipc_action_date"                                        
#>  [30] "application.series_code"                                     
#>  [31] "applicants.applicant_type"                                   
#>  [32] "examiners.examiner_last_name"                                
#>  [33] "patent_type"                                                 
#>  [34] "cpc_current.cpc_subclass_id"                                 
#>  [35] "patent_term_extension"                                       
#>  [36] "us_related_documents.related_doc_published_date"             
#>  [37] "patent_uspc_current_mainclass_average_patent_processing_days"
#>  [38] "patent_year"                                                 
#>  [39] "examiners.examiner_id"                                       
#>  [40] "patent_cpc_current_group_average_patent_processing_days"     
#>  [41] "applicants.applicant_sequence"                               
#>  [42] "examiners.art_group"                                         
#>  [43] "ipcr.ipc_section"                                            
#>  [44] "applicants.applicant_name_last"                              
#>  [45] "wipo_kind"                                                   
#>  [46] "application.rule_47_flag"                                    
#>  [47] "gov_interest_contract_award_numbers.award_number"            
#>  [48] "us_related_documents.related_doc_sequence"                   
#>  [49] "wipo.wipo_sequence"                                          
#>  [50] "patent_num_foreign_documents_cited"                          
#>  [51] "figures.num_figures"                                         
#>  [52] "us_term_of_grant.term_disclaimer"                            
#>  [53] "cpc_current.cpc_class_id"                                    
#>  [54] "ipcr.ipc_classification_data_source"                         
#>  [55] "cpc_current.cpc_sequence"                                    
#>  [56] "gov_interest_statement"                                      
#>  [57] "patent_num_total_documents_cited"                            
#>  [58] "assignees.assignee_state"                                    
#>  [59] "patent_num_us_patents_cited"                                 
#>  [60] "patent_abstract"                                             
#>  [61] "examiners.examiner_first_name"                               
#>  [62] "attorneys.attorney_sequence"                                 
#>  [63] "uspc_at_issue.uspc_mainclass_id"                             
#>  [64] "pct_data.application_kind"                                   
#>  [65] "attorneys.attorney_id"                                       
#>  [66] "ipcr.ipc_class"                                              
#>  [67] "attorneys.attorney_name_first"                               
#>  [68] "pct_data.pct_doc_type"                                       
#>  [69] "inventors.inventor_location_id"                              
#>  [70] "applicants.applicant_name_first"                             
#>  [71] "assignees.assignee_individual_name_first"                    
#>  [72] "ipcr.ipc_symbol_position"                                    
#>  [73] "application.filing_date"                                     
#>  [74] "gov_interest_organizations.level_one"                        
#>  [75] "assignees.assignee_type"                                     
#>  [76] "us_related_documents.published_country"                      
#>  [77] "application.application_type"                                
#>  [78] "us_related_documents.related_doc_type"                       
#>  [79] "ipcr.ipc_main_group"                                         
#>  [80] "assignees.assignee_sequence"                                 
#>  [81] "inventors.inventor_name_first"                               
#>  [82] "foreign_priority.foreign_application_id"                     
#>  [83] "cpc_at_issue.cpc_type"                                       
#>  [84] "us_related_documents.wipo_kind"                              
#>  [85] "gov_interest_organizations.fedagency_name"                   
#>  [86] "inventors.inventor_id"                                       
#>  [87] "ipcr.ipc_classification_value"                               
#>  [88] "applicants.applicant_organization"                           
#>  [89] "pct_data.published_filed_date"                               
#>  [90] "uspc_at_issue.uspc_sequence"                                 
#>  [91] "us_term_of_grant.term_extension"                             
#>  [92] "inventors.inventor_country"                                  
#>  [93] "us_related_documents.related_doc_status"                     
#>  [94] "wipo.wipo_field_id"                                          
#>  [95] "botanic.latin_name"                                          
#>  [96] "us_related_documents.related_doc_kind"                       
#>  [97] "patent_title"                                                
#>  [98] "assignees.assignee_organization"                             
#>  [99] "gov_interest_organizations.level_two"                        
#> [100] "ipcr.ipc_subclass"                                           
#> [101] "assignees.assignee_city"                                     
#> [102] "patent_date"                                                 
#> [103] "inventors.inventor_sequence"                                 
#> [104] "pct_data.pct_371_date"                                       
#> [105] "cpc_at_issue.cpc_group_id"                                   
#> [106] "foreign_priority.priority_claim_sequence"                    
#> [107] "cpc_at_issue.cpc_sequence"                                   
#> [108] "cpc_current.cpc_group_id"                                    
#> [109] "ipcr.ipc_id"                                                 
#> [110] "cpc_at_issue.cpc_class_id"                                   
#> [111] "foreign_priority.filing_date"                                
#> [112] "assignees.assignee_id"                                       
#> [113] "assignees.assignee_location_id"                              
#> [114] "figures.num_sheets"                                          
#> [115] "patent_id"                                                   
#> [116] "applicants.location_id"                                      
#> [117] "patent_detail_desc_length"                                   
#> [118] "patent_earliest_application_date"                            
#> [119] "inventors.inventor_name_last"                                
#> [120] "attorneys.attorney_name_last"                                
#> [121] "cpc_current.cpc_type"                                        
#> [122] "cpc_at_issue.cpc_subclass_id"
```
