---
title: "Examples"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Examples}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



With the recent [API changes](api-changes.html), the patent endpoint is the main way to retrieve data. The other 
endpoints supply additional information.  Also note that an API key is required.

## Patent endpoint

Which patents have been cited by more than 500 US patents?


``` r
library(patentsview)

search_pv(query = qry_funs$gt(patent_num_times_cited_by_us_patents = 500))
#> [1] "https://search.patentsview.org/api/v1/patent/?q=%7B%22_gt%22%3A%7B%22patent_num_times_cited_by_us_patents%22%3A500%7D%7D&f=&s=&o={\"size\":1000,\"after\":\"\"}"
#> $data
#> #### A list with a single data frame on patents level:
#> 
#> List of 1
#>  $ patents:'data.frame':	1000 obs. of  3 variables:
#>   ..$ patent_id   : chr [1:1000] "10004497" ...
#>   ..$ patent_title: chr [1:1000] "Interface systems for use with surgical ins"..
#>   ..$ patent_date : chr [1:1000] "2018-06-26" ...
#> 
#> $query_results
#> #### Distinct entity counts across all downloadable pages of output:
#> 
#> total_hits = 13,199
```

How many distinct inventors are represented by these highly-cited patents?


``` r

search_pv(
  query = qry_funs$gt(patent_num_times_cited_by_us_patents = 500),
  fields = c("patent_id", "inventors.inventor_id")
)
#> [1] "https://search.patentsview.org/api/v1/patent/?q=%7B%22_gt%22%3A%7B%22patent_num_times_cited_by_us_patents%22%3A500%7D%7D&f=[\"patent_id\",\"inventors.inventor_id\"]&s=&o={\"size\":1000,\"after\":\"\"}"
#> $data
#> #### A list with a single data frame (with list column(s) inside) on patents level:
#> 
#> List of 1
#>  $ patents:'data.frame':	1000 obs. of  2 variables:
#>   ..$ patent_id: chr [1:1000] "10004497" ...
#>   ..$ inventors:List of 1000
#> 
#> $query_results
#> #### Distinct entity counts across all downloadable pages of output:
#> 
#> total_hits = 13,199
```
What assignee's organizations start Microsoft?


``` r
query <- qry_funs$begins(assignee_organization = "Microsoft")

pv_out <- search_pv(query, endpoint = "assignee")
#> [1] "https://search.patentsview.org/api/v1/assignee/?q=%7B%22_begins%22%3A%7B%22assignee_organization%22%3A%22Microsoft%22%7D%7D&f=&s=&o={\"size\":1000,\"after\":\"\"}"
pv_out$data$assignees$assignee_organization
#>  [1] "Microsoft Technology Beaming, LLC"               
#>  [2] "MICROSOFT INTERNATIONAL HOLDINGS B.V."           
#>  [3] "Microsoft Mobile Oy"                             
#>  [4] "Microsoft Technology, LLC."                      
#>  [5] "Microsoft Systems Inc."                          
#>  [6] "Microsoft Technology Licensing, LLC"             
#>  [7] "Microsoft Corporation"                           
#>  [8] "Microsoft Patent Licensing, LLC"                 
#>  [9] "Microsoft Corporation—One Microsoft Way"         
#> [10] "Microsoft Licencing Corporation, LLC"            
#> [11] "Microsoft Mobile Internet AB"                    
#> [12] "Microsoft Licensing Technology, LLC"             
#> [13] "Microsoft Technology Learning, LLC"              
#> [14] "Microsoft Israel Research and Development (2002)"
#> [15] "Microsoft Orthopedics Holdings Inc."
```

Where geographically have Microsoft inventors been coming from over the past few years?


``` r
# Write the query
query <- with_qfuns(
  and(
    gte(patent_date = "2022-07-26"), # Dates are in yyyy-mm-dd format
    begins(assignees.assignee_organization = "Microsoft")
  )
)

# Create a field list by getting the inventors fields
inv_fields <- get_fields(endpoint = "patent", groups="inventors")
# Pull the data
pv_out <- search_pv(query, fields = inv_fields, all_pages = TRUE, size = 1000)
#> [1] "https://search.patentsview.org/api/v1/patent/?q=%7B%22_and%22%3A%5B%7B%22_gte%22%3A%7B%22patent_date%22%3A%222022-07-26%22%7D%7D%2C%7B%22_begins%22%3A%7B%22assignees.assignee_organization%22%3A%22Microsoft%22%7D%7D%5D%7D&f=[\"inventors.inventor_id\",\"inventors.inventor_city\",\"inventors.inventor_country\",\"inventors.inventor_name_first\",\"inventors.inventor_name_last\",\"inventors.inventor_sequence\",\"inventors.inventor_state\",\"patent_id\"]&s=[{\"patent_id\":\"asc\"}]&o={\"size\":1000,\"after\":\"\"}"
#> [1] "https://search.patentsview.org/api/v1/patent/?q=%7B%22_and%22%3A%5B%7B%22_gte%22%3A%7B%22patent_date%22%3A%222022-07-26%22%7D%7D%2C%7B%22_begins%22%3A%7B%22assignees.assignee_organization%22%3A%22Microsoft%22%7D%7D%5D%7D&f=[\"inventors.inventor_id\",\"inventors.inventor_city\",\"inventors.inventor_country\",\"inventors.inventor_name_first\",\"inventors.inventor_name_last\",\"inventors.inventor_sequence\",\"inventors.inventor_state\",\"patent_id\"]&s=[{\"patent_id\":\"asc\"}]&o={\"size\":1000,\"after\":\"\"}"
#> [1] "https://search.patentsview.org/api/v1/patent/?q=%7B%22_and%22%3A%5B%7B%22_gte%22%3A%7B%22patent_date%22%3A%222022-07-26%22%7D%7D%2C%7B%22_begins%22%3A%7B%22assignees.assignee_organization%22%3A%22Microsoft%22%7D%7D%5D%7D&f=[\"inventors.inventor_id\",\"inventors.inventor_city\",\"inventors.inventor_country\",\"inventors.inventor_name_first\",\"inventors.inventor_name_last\",\"inventors.inventor_sequence\",\"inventors.inventor_state\",\"patent_id\"]&s=[{\"patent_id\":\"asc\"}]&o={\"size\":1000,\"after\":\"11567995\"}"
#> [1] "https://search.patentsview.org/api/v1/patent/?q=%7B%22_and%22%3A%5B%7B%22_gte%22%3A%7B%22patent_date%22%3A%222022-07-26%22%7D%7D%2C%7B%22_begins%22%3A%7B%22assignees.assignee_organization%22%3A%22Microsoft%22%7D%7D%5D%7D&f=[\"inventors.inventor_id\",\"inventors.inventor_city\",\"inventors.inventor_country\",\"inventors.inventor_name_first\",\"inventors.inventor_name_last\",\"inventors.inventor_sequence\",\"inventors.inventor_state\",\"patent_id\"]&s=[{\"patent_id\":\"asc\"}]&o={\"size\":1000,\"after\":\"11745094\"}"
#> [1] "https://search.patentsview.org/api/v1/patent/?q=%7B%22_and%22%3A%5B%7B%22_gte%22%3A%7B%22patent_date%22%3A%222022-07-26%22%7D%7D%2C%7B%22_begins%22%3A%7B%22assignees.assignee_organization%22%3A%22Microsoft%22%7D%7D%5D%7D&f=[\"inventors.inventor_id\",\"inventors.inventor_city\",\"inventors.inventor_country\",\"inventors.inventor_name_first\",\"inventors.inventor_name_last\",\"inventors.inventor_sequence\",\"inventors.inventor_state\",\"patent_id\"]&s=[{\"patent_id\":\"asc\"}]&o={\"size\":1000,\"after\":\"11922001\"}"

# Unnest the inventor list column
unnest_pv_data(pv_out$data, "patent_id")
#> List of 2
#>  $ inventors:'data.frame':	14533 obs. of  8 variables:
#>   ..$ patent_id          : chr [1:14533] "11397055" ...
#>   ..$ inventor           : chr [1:14533] "https://search.patentsview.org/api/"..
#>   ..$ inventor_name_first: chr [1:14533] "Tzu-Yuan" ...
#>   ..$ inventor_name_last : chr [1:14533] "Lin" ...
#>   ..$ inventor_city      : chr [1:14533] "San Jose" ...
#>   ..$ inventor_state     : chr [1:14533] "CA" ...
#>   ..$ inventor_country   : chr [1:14533] "US" ...
#>   ..$ inventor_sequence  : int [1:14533] 1 2 ...
#>  $ patents  :'data.frame':	3600 obs. of  1 variable:
#>   ..$ patent_id: chr [1:3600] "11397055" ...
```

## Inventor Endpoint

Which inventor's most recent patent has Chicago, IL listed as their location.


``` r
pv_out <- search_pv(
  query = '{"_and":[{"_text_phrase": {"inventor_lastknown_city":"Chicago"}},
                    {"_text_phrase": {"inventor_lastknown_state":"IL"}}]}',
  endpoint = "inventor"
)
#> [1] "https://search.patentsview.org/api/v1/inventor/?q=%7B%22_and%22%3A%5B%7B%22_text_phrase%22%3A%20%7B%22inventor_lastknown_city%22%3A%22Chicago%22%7D%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%22_text_phrase%22%3A%20%7B%22inventor_lastknown_state%22%3A%22IL%22%7D%7D%5D%7D&f=&s=&o={\"size\":1000,\"after\":\"\"}"
#> Waiting 31s for retry backoff ■■ Waiting 31s for retry backoff ■■ Waiting 31s
#> for retry backoff ■■ Waiting 31s for retry backoff ■■■ Waiting 31s for retry
#> backoff ■■■ Waiting 31s for retry backoff ■■■ Waiting 31s for retry backoff ■■■
#> Waiting 31s for retry backoff ■■■ Waiting 31s for retry backoff ■■■ Waiting 31s
#> for retry backoff ■■■■ Waiting 31s for retry backoff ■■■■ Waiting 31s for retry
#> backoff ■■■■ Waiting 31s for retry backoff ■■■■ Waiting 31s for retry backoff
#> ■■■■ Waiting 31s for retry backoff ■■■■■ Waiting 31s for retry backoff ■■■■■
#> Waiting 31s for retry backoff ■■■■■ Waiting 31s for retry backoff ■■■■■ Waiting
#> 31s for retry backoff ■■■■■■ Waiting 31s for retry backoff ■■■■■■ Waiting 31s
#> for retry backoff ■■■■■■ Waiting 31s for retry backoff ■■■■■■ Waiting 31s for
#> retry backoff ■■■■■■ Waiting 31s for retry backoff ■■■■■■■ Waiting 31s for
#> retry backoff ■■■■■■■ Waiting 31s for retry backoff ■■■■■■■ Waiting 31s for
#> retry backoff ■■■■■■■ Waiting 31s for retry backoff ■■■■■■■ Waiting 31s for
#> retry backoff ■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■ Waiting 31s for
#> retry backoff ■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■ Waiting 31s for
#> retry backoff ■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■ Waiting 31s for
#> retry backoff ■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■ Waiting 31s for
#> retry backoff ■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■ Waiting 31s for
#> retry backoff ■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■ Waiting 31s
#> for retry backoff ■■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■ Waiting
#> 31s for retry backoff ■■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■
#> Waiting 31s for retry backoff ■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■■ Waiting 31s for retry
#> backoff ■■■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■■ Waiting 31s for
#> retry backoff ■■■■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■■■ Waiting
#> 31s for retry backoff ■■■■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■■■
#> Waiting 31s for retry backoff ■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■■■■ Waiting 31s for retry
#> backoff ■■■■■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■■■■ Waiting 31s
#> for retry backoff ■■■■■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■■■■■
#> Waiting 31s for retry backoff ■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■■■■■ Waiting 31s for
#> retry backoff ■■■■■■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■■■■■■
#> Waiting 31s for retry backoff ■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■■■■■■ Waiting 31s for
#> retry backoff ■■■■■■■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■■■■■■■
#> Waiting 31s for retry backoff ■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■■■■■■■ Waiting 31s for
#> retry backoff ■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■■■■■■■■
#> Waiting 31s for retry backoff ■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■■■■■■■■ Waiting 31s
#> for retry backoff ■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■■■■■■■■■ Waiting 31s
#> for retry backoff ■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■■■■■■■■■ Waiting 31s
#> for retry backoff ■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■■■■■■■■■■ Waiting
#> 31s for retry backoff ■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■■■■■■■■■■■ Waiting
#> 31s for retry backoff ■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■■■■■■■■■■■ Waiting
#> 31s for retry backoff ■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■■■■■■■■■■■■
#> Waiting 31s for retry backoff ■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■
#> Waiting 31s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■
#> Waiting 31s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■■
#> Waiting 31s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■■■
#> Waiting 31s for retry backoff ■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry
#> backoff ■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ Waiting 31s for retry backoff
#> ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

pv_out
#> $data
#> #### A list with a single data frame on inventors level:
#> 
#> List of 1
#>  $ inventors:'data.frame':	1000 obs. of  3 variables:
#>   ..$ inventor_id        : chr [1:1000] "001sh51t5ft5hbegqhzo1y4or" ...
#>   ..$ inventor_name_first: chr [1:1000] "Michael M." ...
#>   ..$ inventor_name_last : chr [1:1000] "Stamler" ...
#> 
#> $query_results
#> #### Distinct entity counts across all downloadable pages of output:
#> 
#> total_hits = 13,447
```
 In the new version of the API, the behavior of this endpoint has changed.  See the similar example
on the [legacy inventors endpoint](https://patentsview.org/apis/api-endpoints/inventors) page
for its original behavior.

We could also call the new version of the patent endpoint to find inventors who listed
Chicago, IL as their location when applying for a patent.


``` r
fields <- c("patent_id", get_fields('patent', groups="inventors"))
fields
#> [1] "patent_id"                     "inventors.inventor_id"        
#> [3] "inventors.inventor_city"       "inventors.inventor_country"   
#> [5] "inventors.inventor_name_first" "inventors.inventor_name_last" 
#> [7] "inventors.inventor_sequence"   "inventors.inventor_state"

query <- '{"_and":[{"_text_phrase": {"inventors.inventor_city":"Chicago"}},
                   {"_text_phrase": {"inventors.inventor_state":"IL"}}]}'

search_pv(query, fields=fields, endpoint="patent")
#> [1] "https://search.patentsview.org/api/v1/patent/?q=%7B%22_and%22%3A%5B%7B%22_text_phrase%22%3A%20%7B%22inventors.inventor_city%22%3A%22Chicago%22%7D%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%22_text_phrase%22%3A%20%7B%22inventors.inventor_state%22%3A%22IL%22%7D%7D%5D%7D&f=[\"patent_id\",\"inventors.inventor_id\",\"inventors.inventor_city\",\"inventors.inventor_country\",\"inventors.inventor_name_first\",\"inventors.inventor_name_last\",\"inventors.inventor_sequence\",\"inventors.inventor_state\"]&s=&o={\"size\":1000,\"after\":\"\"}"
#> $data
#> #### A list with a single data frame (with list column(s) inside) on patents level:
#> 
#> List of 1
#>  $ patents:'data.frame':	1000 obs. of  2 variables:
#>   ..$ patent_id: chr [1:1000] "10000578" ...
#>   ..$ inventors:List of 1000
#> 
#> $query_results
#> #### Distinct entity counts across all downloadable pages of output:
#> 
#> total_hits = 46,544
```

Note that here all the inventors on a particular patent will be returned, not just the ones whose
location was Chicago, IL.  Also see the [Writing Queries Vignette](writing-queries.html) for more readable ways
to write queries.

## Assignee Endpoint

Which assignees have an interest in beer?


``` r
search_pv(
  query = qry_funs$contains(patent_title = "beer"),
  endpoint = "patent"
)
#> [1] "https://search.patentsview.org/api/v1/patent/?q=%7B%22_contains%22%3A%7B%22patent_title%22%3A%22beer%22%7D%7D&f=&s=&o={\"size\":1000,\"after\":\"\"}"
#> $data
#> #### A list with a single data frame on patents level:
#> 
#> List of 1
#>  $ patents:'data.frame':	592 obs. of  3 variables:
#>   ..$ patent_id   : chr [1:592] "10000326" ...
#>   ..$ patent_title: chr [1:592] "Plastic beer keg" ...
#>   ..$ patent_date : chr [1:592] "2018-06-19" ...
#> 
#> $query_results
#> #### Distinct entity counts across all downloadable pages of output:
#> 
#> total_hits = 592
```
