---
title: "Getting started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



The new version of the API requires an API key, or all of your requests will be rejected. Request an 
API key using this link: <https://patentsview.org/apis/keyrequest> Once you have one, you’ll need to set 
an environmental variable PATENTSVIEW_API_KEY to the value of your API key for the R package to use.


## A basic example 

Let's start with a basic example of how to use the package's primary function, `search_pv()`:


``` r
library(patentsview)

search_pv(
  query = '{"_gte":{"patent_date":"2007-01-01"}}',
  endpoint = "patent"
)
#> $data
#> #### A list with a single data frame on patents level:
#> 
#> List of 1
#>  $ patents:'data.frame':	1000 obs. of  3 variables:
#>   ..$ patent_id   : chr [1:1000] "7155746" ...
#>   ..$ patent_title: chr [1:1000] "Anti-wicking protective workwear and method"..
#>   ..$ patent_date : chr [1:1000] "2007-01-02" ...
#> 
#> $query_results
#> #### Distinct entity counts across all downloadable pages of output:
#> 
#> total_hits = 5,452,372, count = 1,000
```

This call to `search_pv()` sends our query to the patent endpoint (the default). The API has 27 endpoints, corresponding to 26 different entity types.
patent/rel_app_text and publication/rel_app_text both both return a rel_app_text entity, though
they are slightly different.   Here is the list of entities the API returns:
assignees, attorneys, cpc_classes, cpc_groups, cpc_subclasses,  foreign_citations, 
g_brf_sum_texts, g_claims, g_detail_desc_texts, g_draw_desc_texts,
inventors, ipcs, locations, otherreferences, 
pg_brf_sum_texts, pg_claims, pg_detail_desc_texts, pg_draw_desc_texts,
patents, publications, rel_app_texts, us_application_citations, 
us_patent_citations, uspc_mainclasses, uspc_subclasses, wipo.[^1] 
Your choice of endpoint determines which entity your query is applied to, as well as the structure of the data that is returned (more on this in the "27 endpoints for 27 entities section"). For now, let's turn our attention to the `query` parameter. 

## Writing queries

The PatentsView query syntax is documented on their [query language page](https://search.patentsview.org/docs/docs/Search%20API/SearchAPIReference/#api-query-language) note also the change to the Options parameter for the new version of the API mentioned on that page.[^2] However, it can be difficult to get your query right if you're writing it by hand (i.e., just writing the query in a string like `'{"_gte":{"patent_date":"2007-01-01"}}'`, as we did in the example shown above). The `patentsview` package comes with a simple domain specific language (DSL) to make writing queries a breeze. I recommend using the functions in this DSL for all but the most basic queries, especially if you're encountering errors and don't understand why. To get a feel for how it works, let's rewrite the query shown above using one of the functions in the DSL, `qry_funs$gte()`:


``` r
qry_funs$gte(patent_date = "2007-01-01")
#> {"_gte":{"patent_date":"2007-01-01"}}
```

More complex queries are also possible:


``` r
with_qfuns(
  and(
    gte(patent_date = "2007-01-01"),
    text_phrase(patent_abstract = c("computer program", "dog leash"))
  )
)
#> {"_and":[{"_gte":{"patent_date":"2007-01-01"}},{"_or":[{"_text_phrase":{"patent_abstract":"computer program"}},{"_text_phrase":{"patent_abstract":"dog leash"}}]}]}
```

Check out the [writing queries vignette](writing-queries.html) for more details on using the DSL.

## Fields

Each endpoint has a different set of fields. The new version of the API allows all fields to be queried. In the first example, we didn't specify which fields we wanted to retrieve so we were given the default set. You can specify which fields you want using the `fields` argument:


``` r
# search_pv defaults the endpoint parameter to "patents" if not specified
result = search_pv(
  query = '{"_gte":{"patent_date":"2007-01-01"}}',
  fields = c("patent_id", "patent_title")
)
result
#> $data
#> #### A list with a single data frame on patents level:
#> 
#> List of 1
#>  $ patents:'data.frame':	1000 obs. of  2 variables:
#>   ..$ patent_id   : chr [1:1000] "7155746" ...
#>   ..$ patent_title: chr [1:1000] "Anti-wicking protective workwear and method"..
#> 
#> $query_results
#> #### Distinct entity counts across all downloadable pages of output:
#> 
#> total_hits = 5,452,372, count = 1,000
```

To list all of the fields for a given endpoint, use `get_fields()`:


``` r
retrvble_flds <- get_fields(endpoint = "patent")
head(retrvble_flds)
#> [1] "applicants.applicant_designation"  "applicants.applicant_name_first"  
#> [3] "applicants.applicant_name_last"    "applicants.applicant_organization"
#> [5] "applicants.applicant_sequence"     "applicants.applicant_type"
```
Nested fields can be fully qualified or a new API shorthand can be used, where group names can specified. When group names are used, all of the group’s nested fields will be returned by the API. E.g., the new version of the API and R package will accept ```fields=c("applicants")```

See the [Swagger UI page](https://search.patentsview.org/swagger-ui/) for the API, the fields returned are listed for each endpoint in the 200 Response body sections.  The [API's endpoint documentation](https://search.patentsview.org/docs/docs/Search%20API/SearchAPIReference/#endpoints) has a similar look and feel.

You can also visit an endpoint's online documentation page to see a list of its fields (e.g., see the [inventor field list table](https://search.patentsview.org/docs/docs/Search%20API/SearchAPIReference/#inventor)). In earlier versions of the API not all fields were queryable as they are now. The field tables for all of the endpoints can be found in the `fieldsdf` data frame, which you can load using `data("fieldsdf")` or `View(patentsview::fieldsdf)`.

**An important note: PatentsView uses disambiguated versions of assignees, inventors, and locations, instead of raw data.** For example, let's say you search for all inventors whose first name is "john." The PatentsView API is going to return all of the inventors who have a preferred first name (as per the disambiguation results) of john, which may not necessarily be their raw first name. You could be getting back inventors whose first name appears on the patent as, say, "jonathan," "johnn," or even "john jay.", see the [PatentsView Inventor Disambiguation Technical Workshop website](https://patentsview.org/disambiguation).

In the original version of the API, rawinventor_first_name and rawinventor_last_name were available from the patents, inventors and assignees endpoints. **In the new version of the API these fields are no longer available.**

## Paginated responses

By default, `search_pv()` returns 1,000 records per page and only gives you the first page of results. I suggest starting with something smaller, like the `size` = 150 below, while you're figuring out the details of your request, such as the query you want to use and the fields you want returned. Once you have those items finalized, you can use the `size` argument to download up to 1,000 records per page. 

You can download all pages of output in one call by setting `all_pages = TRUE`. This will set `size` equal to 1,000 and loop over all pages of output:


``` r
search_pv(
  query = qry_funs$eq(inventors.inventor_name_last = "Chambers"),
  all_pages = TRUE, size = 1000
)
#> $data
#> #### A list with a single data frame on patents level:
#> 
#> List of 1
#>  $ patents:'data.frame':	1210 obs. of  3 variables:
#>   ..$ patent_id   : chr [1:1210] "3931611" ...
#>   ..$ patent_title: chr [1:1210] "Program event recorder and data processing "..
#>   ..$ patent_date : chr [1:1210] "1976-01-06" ...
#> 
#> $query_results
#> #### Distinct entity counts across all downloadable pages of output:
#> 
#> total_hits = 2,487, count = 1,000
```

## Entity counts

Our last two calls to `search_pv()` gave the same value for `total_hits`, even though we got a lot more data from the second call. This is because the entity counts returned by the API refer to the number of distinct entities across all *downloadable pages of output*, not just the page that was returned.


## 27 endpoints for 26 entities

With the recent API change, the patent endpoint supplies the basic patent data and the other endpoints return more specific data for those patents.


``` r

query <- qry_funs$eq(inventors.inventor_name_last = "Chambers")

# Here we'll request patent_id and the inventor fields from the patent endpoint
inv_fields <- get_fields(endpoint = "patent", groups ="inventors")
inv_fields
#> [1] "inventors.inventor_id"         "inventors.inventor_city"      
#> [3] "inventors.inventor_country"    "inventors.inventor_name_first"
#> [5] "inventors.inventor_name_last"  "inventors.inventor_sequence"  
#> [7] "inventors.inventor_state"
fields <- c(inv_fields, "patent_id")

result <- search_pv(query, endpoint = "patent", fields = fields)
result
#> $data
#> #### A list with a single data frame (with list column(s) inside) on patents level:
#> 
#> List of 1
#>  $ patents:'data.frame':	1000 obs. of  2 variables:
#>   ..$ patent_id: chr [1:1000] "3931611" ...
#>   ..$ inventors:List of 1000
#> 
#> $query_results
#> #### Distinct entity counts across all downloadable pages of output:
#> 
#> total_hits = 2,487, count = 1,000

# Here's the first inventors
result$data$patents$inventors[[1]]
#>                                                               inventor
#> 1     https://search.patentsview.org/api/v1/inventor/fl:gl_ln:grant-3/
#> 2 https://search.patentsview.org/api/v1/inventor/fl:da_ln:chambers-11/
#>   inventor_name_first inventor_name_last inventor_city inventor_state
#> 1               Glenn              Grant      San Jose             CA
#> 2               David           Chambers     Cupertino             CA
#>   inventor_country inventor_sequence
#> 1               US                 0
#> 2               US                 1

# Now we will see what the inventor endpoint returns for a similar query.
# We use get_fields() to get all the available for the inventor endpoint.
query <- qry_funs$eq(inventor_name_last = "Chambers")
fields <- get_fields(endpoint = "inventor")

search_pv(query, endpoint = "inventor", fields = fields)
#> Error in `httr2::req_perform()`:
#> ! HTTP 400 Bad Request.
#> • Invalid field: inventor_years.num_patents. inventor_years is not a nested field
```

Your choice of endpoint determines two things:

1. **Which entity your query is applied to.** The first call shown above used the patent endpoint, so the API searched for patents that have at least one inventor listed on them with the last name "Chambers." The second call used the inventor endpoint to show what it returns for a similar query.

2. **The structure of the data frame that is returned.** The first call returned a data frame on the patent level, meaning that each row corresponded to a different patent. Fields that were not on the patent level (e.g., `inventors.inventor_name_last`) were returned in list columns that are named after the entity associated with the field (e.g., the `inventors` entity).[^3] Meanwhile, the second call gave us a data frame on the inventor level (one row for each inventor) because it used the inventor endpoint.

Most of the time you will want to use the patent endpoint. Note that you can still effectively filter on fields that are not at the patent-level when using the patent endpoint (e.g., you can filter on assignee name or CPC category). This is because patents are relatively low-level entities. For higher level entities like assignees, if you filter on a field that is not at the assignee-level (e.g., inventor name), the API will return data on any assignee that has at least one inventor whose name matches your search, which is probably not what you want.

## Casting fields

The API now returns most data fields as an appropriate data type (e.g., numeric). There are, however,
a few fields that are returned as strings rather than integers and there are a lot of date fields now.
There are also two rule_47_flags, one returned by the patent endpoint, the other by the publication endpoint.
The former is a boolean while the latter is a string that can be cast to a boolean.  Lastly, most
of the document numbers are numeric though there are two instances where they are strings that can
be cast to integers.  You can cast all fields to their preferred R types using `cast_pv_data()`:


``` r
library(knitr)

# These fields are received as strings and would be cast to integers
ints <- fieldsdf[fieldsdf$data_type == "int", c("endpoint","field")]
ints <- ints[order(ints$field),]
print(ints,  row.names = FALSE)
#>                        endpoint                    field
#>                        assignee            assignee_type
#>                          patent  assignees.assignee_type
#>                     publication  assignees.assignee_type
#>  patent/us_application_citation citation_document_number

# These fields are received as strings and would be cast to dates
date_fields <- fieldsdf[fieldsdf$data_type == "date", c("endpoint","field")]
kable(date_fields, row.names = FALSE)
```



|endpoint                       |field                                           |
|:------------------------------|:-----------------------------------------------|
|assignee                       |assignee_first_seen_date                        |
|assignee                       |assignee_last_seen_date                         |
|cpc_class                      |cpc_class_first_seen_date                       |
|cpc_class                      |cpc_class_last_seen_date                        |
|cpc_subclass                   |cpc_subclass_first_seen_date                    |
|cpc_subclass                   |cpc_subclass_last_seen_date                     |
|inventor                       |inventor_first_seen_date                        |
|inventor                       |inventor_last_seen_date                         |
|patent                         |application.filing_date                         |
|patent                         |foreign_priority.filing_date                    |
|patent                         |ipcr.ipc_action_date                            |
|patent                         |patent_date                                     |
|patent                         |patent_earliest_application_date                |
|patent                         |pct_data.pct_102_date                           |
|patent                         |pct_data.pct_371_date                           |
|patent                         |pct_data.published_filed_date                   |
|patent                         |us_related_documents.related_doc_published_date |
|patent                         |us_term_of_grant.disclaimer_date                |
|patent/attorney                |attorney_first_seen_date                        |
|patent/attorney                |attorney_last_seen_date                         |
|patent/foreign_citation        |citation_date                                   |
|patent/us_application_citation |citation_date                                   |
|patent/us_patent_citation      |citation_date                                   |
|publication                    |cpc_at_issue.action_date                        |
|publication                    |foreign_priority.filing_date                    |
|publication                    |ipcr.ipc_action_date                            |
|publication                    |pct_data.pct_102_date                           |
|publication                    |pct_data.pct_371_date                           |
|publication                    |pct_data.published_filed_date                   |
|publication                    |publication_date                                |
|publication                    |us_related_documents.related_doc_published_date |
|uspc_mainclass                 |uspc_mainclass_first_seen_date                  |
|uspc_mainclass                 |uspc_mainclass_last_seen_date                   |



``` r

res <- search_pv(
  query = '{"patent_id":"5116621"}', 
  fields = c("patent_id", "patent_date", "patent_title", "patent_year", "assignees.assignee_type")
)

# unnest_pv_data shows that the assignee_type field is received as a string and patent_year
# is received as an integer
unnest_pv_data(res$data)
#> List of 2
#>  $ assignees:'data.frame':	2 obs. of  2 variables:
#>   ..$ patent_id    : chr [1:2] "5116621" ...
#>   ..$ assignee_type: chr [1:2] "3" ...
#>  $ patents  :'data.frame':	1 obs. of  4 variables:
#>   ..$ patent_id   : chr "5116621"
#>   ..$ patent_title: chr "Anti-inflammatory analgesic patch"
#>   ..$ patent_date : chr "1992-05-26"
#>   ..$ patent_year : int 1992

# cast_pv_data will convert the string patent_date to an R date and assignee_type to an integer
recast <- cast_pv_data(res$data)
unnest_pv_data(recast)
#> List of 2
#>  $ assignees:'data.frame':	2 obs. of  2 variables:
#>   ..$ patent_id    : chr [1:2] "5116621" ...
#>   ..$ assignee_type: int [1:2] 3 3
#>  $ patents  :'data.frame':	1 obs. of  4 variables:
#>   ..$ patent_id   : chr "5116621"
#>   ..$ patent_title: chr "Anti-inflammatory analgesic patch"
#>   ..$ patent_date : Date[1:1], format: "1992-05-26"
#>   ..$ patent_year : int 1992
```

## FAQs

#### I'm sure my query is well formatted and correct but I keep getting an error. What's the deal?

The API query syntax guidelines do not cover all of the API's behavior. Specifically, there are several things that you cannot do which are not documented on the API's webpage. The [writing queries vignette](writing-queries.html) has more details on this. You can also try the string version of your query in the API's [Swagger UI page](https://search.patentsview.org/swagger-ui/).  Its error messages can sometimes help determine the problem.

Now that the R package is using httr2, users can make use of its last_request() method to see what was sent to the API. This could be useful when trying to fix an invalid request.
```
httr2::last_request()
```

#### Does the API have any rate limiting/throttling controls?

Yes, the API currently allows 45 calls per minute for each API key.  If this limit is exceeded the API will return an http status of 429 with a response header Retry-After set to the number of seconds to wait before making subsequent requests.  The R package should handle this for you.  You will need to [request an API key](https://patentsview.org/apis/keyrequest) and set the environmental variable PATENTSVIEW_API_KEY to the value of your key.

#### How do I access the data frames inside the list columns returned by `search_pv()`?

Let’s consider the following data, in which assignees are the primary entity while applications and “government interest statements” are the secondary entities (also referred to as subentities):
Government interests fields are no longer present


``` r
# Create field list -
fields <- get_fields("patent")

# Pull data
res <- search_pv(
  query = qry_funs$text_any(inventors.inventor_name_last = "Smith"), 
  endpoint = "patent", 
  fields = fields
)
res$data
#> #### A list with a single data frame (with list column(s) inside) on patents level:
#> 
#> List of 1
#>  $ patents:'data.frame':	1000 obs. of  34 variables:
#>   ..$ patent_id                                                   : chr [1:10"..
#>   ..$ patent_title                                                : chr [1:10"..
#>   ..$ patent_type                                                 : chr [1:10"..
#>   ..$ patent_date                                                 : chr [1:10"..
#>   ..$ patent_year                                                 : int [1:100..
#>   ..$ patent_abstract                                             : chr [1:10"..
#>   ..$ patent_cpc_current_group_average_patent_processing_days     : int [1:100..
#>   ..$ patent_detail_desc_length                                   : int [1:100..
#>   ..$ patent_earliest_application_date                            : chr [1:10"..
#>   ..$ patent_num_foreign_documents_cited                          : int [1:100..
#>   ..$ patent_num_times_cited_by_us_patents                        : int [1:100..
#>   ..$ patent_num_total_documents_cited                            : int [1:100..
#>   ..$ patent_num_us_applications_cited                            : int [1:100..
#>   ..$ patent_num_us_patents_cited                                 : int [1:100..
#>   ..$ patent_processing_days                                      : int [1:100..
#>   ..$ patent_term_extension                                       : logi [1:10..
#>   ..$ gov_interest_statement                                      : chr [1:100..
#>   ..$ patent_uspc_current_mainclass_average_patent_processing_days: int [1:100..
#>   ..$ application                                                 :List of 1000
#>   ..$ assignees                                                   :List of 1000
#>   ..$ attorneys                                                   :List of 1000
#>   ..$ cpc_current                                                 :List of 1000
#>   ..$ examiners                                                   :List of 1000
#>   ..$ foreign_priority                                            :List of 1000
#>   ..$ figures                                                     :List of 1000
#>   ..$ granted_pregrant_crosswalk                                  :List of 1000
#>   ..$ inventors                                                   :List of 1000
#>   ..$ ipcr                                                        :List of 1000
#>   ..$ uspc_at_issue                                               :List of 1000
#>   ..$ wipo                                                        :List of 1000
#>   ..$ wipo_kind                                                   : chr [1:10"..
#>   ..$ us_term_of_grant                                            :List of 1000
#>   ..$ gov_interest_organizations                                  :List of 1000
#>   ..$ gov_interest_contract_award_numbers                         :List of 1000
```

`res$data` has vector columns for those fields that belong to the primary entity (e.g., `res$data$patent_year`) and list columns for those fields that belong to any secondary entity (e.g., `res$data$assignees$assignee_organization`). You have two good ways to pull out the data frames that are nested inside these list columns: 

1. **Use tidyr::unnest.** (This is probably the easier choice of the two). 


``` r
library(tidyr)

# Get assignee data:
res$data$patents %>% 
  unnest(assignees) %>%
  head()
#> # A tibble: 6 × 42
#>   patent_id patent_title paten…¹ paten…² paten…³ paten…⁴ paten…⁵ paten…⁶ paten…⁷
#>   <chr>     <chr>        <chr>   <chr>     <int> <chr>     <int>   <int> <chr>  
#> 1 3930365   Fuel contro… utility 1976-0…    1976 A fuel…     746   11965 1974-0…
#> 2 3930518   Valves       utility 1976-0…    1976 In a f…     715    6493 1974-0…
#> 3 3930607   Container a… utility 1976-0…    1976 A tubu…     544   36340 1975-0…
#> 4 3930635   Leak-proof … utility 1976-0…    1976 Extern…     715   11698 1974-0…
#> 5 3930874   Bonded fuse… utility 1976-0…    1976 Basic …     836    6680 1974-0…
#> 6 3930915   Method of m… utility 1976-0…    1976 A bind…     717   20419 1974-0…
#> # … with 33 more variables: patent_num_foreign_documents_cited <int>,
#> #   patent_num_times_cited_by_us_patents <int>,
#> #   patent_num_total_documents_cited <int>,
#> #   patent_num_us_applications_cited <int>, patent_num_us_patents_cited <int>,
#> #   patent_processing_days <int>, patent_term_extension <lgl>,
#> #   gov_interest_statement <chr>,
#> #   patent_uspc_current_mainclass_average_patent_processing_days <int>, …
```

2. **Use patentsview::unnest_pv_data.** `unnest_pv_data()` creates a series of data frames (one for each entity level) that are like tables in a relational database. You provide it with the data returned by `search_pv()` and a field that can act as a unique identifier for the primary entities:


``` r
unnest_pv_data(data = res$data, pk = "patent_id")
#> List of 16
#>  $ application                        :'data.frame':	1000 obs. of  7 variables:
#>   ..$ patent_id       : chr [1:1000] "3930365" ...
#>   ..$ application_id  : chr [1:1000] "05/489742" ...
#>   ..$ application_type: chr [1:1000] "05" ...
#>   ..$ filing_date     : chr [1:1000] "1974-07-18" ...
#>   ..$ series_code     : chr [1:1000] "05" ...
#>   ..$ rule_47_flag    : logi [1:1000] FALSE ...
#>   ..$ filing_type     : chr [1:1000] "05" ...
#>  $ assignees                          :'data.frame':	841 obs. of  10 variables:
#>   ..$ patent_id                     : chr [1:841] "3930365" ...
#>   ..$ assignee                      : chr [1:841] "https://search.patentsview"..
#>   ..$ assignee_type                 : chr [1:841] "3" ...
#>   ..$ assignee_individual_name_first: chr [1:841] NA ...
#>   ..$ assignee_individual_name_last : chr [1:841] NA ...
#>   ..$ assignee_organization         : chr [1:841] "Joseph Lucas (Industries) "..
#>   ..$ assignee_city                 : chr [1:841] NA ...
#>   ..$ assignee_state                : chr [1:841] NA ...
#>   ..$ assignee_country              : chr [1:841] NA ...
#>   ..$ assignee_sequence             : int [1:841] 0 0 ...
#>  $ attorneys                          :'data.frame':	1274 obs. of  6 variables:
#>   ..$ patent_id            : chr [1:1274] "3930365" ...
#>   ..$ attorney_id          : chr [1:1274] "9d09de38cd429c759bb62d889befa5c6" ...
#>   ..$ attorney_sequence    : int [1:1274] 0 0 ...
#>   ..$ attorney_name_first  : chr [1:1274] NA ...
#>   ..$ attorney_name_last   : chr [1:1274] NA ...
#>   ..$ attorney_organization: chr [1:1274] "Holman & Stern" ...
#>  $ cpc_current                        :'data.frame':	3473 obs. of  8 variables:
#>   ..$ patent_id      : chr [1:3473] "3930365" ...
#>   ..$ cpc_sequence   : int [1:3473] 0 0 ...
#>   ..$ cpc_class      : chr [1:3473] "https://search.patentsview.org/api/v1/cp"..
#>   ..$ cpc_class_id   : chr [1:3473] "F02" ...
#>   ..$ cpc_subclass   : chr [1:3473] "https://search.patentsview.org/api/v1/cp"..
#>   ..$ cpc_subclass_id: chr [1:3473] "F02C" ...
#>   ..$ cpc_group      : chr [1:3473] "https://search.patentsview.org/api/v1/cp"..
#>   ..$ cpc_group_id   : chr [1:3473] "F02C7/26" ...
#>  $ examiners                          :'data.frame':	1374 obs. of  6 variables:
#>   ..$ patent_id          : chr [1:1374] "3930365" ...
#>   ..$ examiner_id        : chr [1:1374] "g8yy414r0f845vv5jw60ra2bb" ...
#>   ..$ examiner_first_name: chr [1:1374] "Clarence R." ...
#>   ..$ examiner_last_name : chr [1:1374] "Gordon" ...
#>   ..$ examiner_role      : chr [1:1374] "primary" ...
#>   ..$ art_group          : logi [1:1374] NA ...
#>  $ foreign_priority                   :'data.frame':	173 obs. of  6 variables:
#>   ..$ patent_id              : chr [1:173] "3930365" ...
#>   ..$ priority_claim_sequence: int [1:173] 0 0 ...
#>   ..$ priority_claim_kind    : logi [1:173] NA ...
#>   ..$ foreign_application_id : chr [1:173] "34135/74" ...
#>   ..$ filing_date            : chr [1:173] "1974-07-18" ...
#>   ..$ foreign_country_filed  : chr [1:173] "UK" ...
#>  $ figures                            :'data.frame':	801 obs. of  3 variables:
#>   ..$ patent_id  : chr [1:801] "3930365" ...
#>   ..$ num_figures: int [1:801] 3 6 ...
#>   ..$ num_sheets : int [1:801] 3 5 ...
#>  $ granted_pregrant_crosswalk         :'data.frame':	1000 obs. of  3 variables:
#>   ..$ patent_id         : chr [1:1000] "3930365" ...
#>   ..$ document_number   : logi [1:1000] NA ...
#>   ..$ application_number: chr [1:1000] "05489742" ...
#>  $ inventors                          :'data.frame':	1877 obs. of  8 variables:
#>   ..$ patent_id          : chr [1:1877] "3930365" ...
#>   ..$ inventor           : chr [1:1877] "https://search.patentsview.org/api/v"..
#>   ..$ inventor_name_first: chr [1:1877] "Trevor S." ...
#>   ..$ inventor_name_last : chr [1:1877] "Smith" ...
#>   ..$ inventor_city      : chr [1:1877] NA ...
#>   ..$ inventor_state     : chr [1:1877] NA ...
#>   ..$ inventor_country   : chr [1:1877] NA ...
#>   ..$ inventor_sequence  : int [1:1877] 0 1 ...
#>  $ ipcr                               :'data.frame':	1365 obs. of  11 variables:
#>   ..$ patent_id                     : chr [1:1365] "3930365" ...
#>   ..$ ipc_sequence                  : int [1:1365] 0 0 ...
#>   ..$ ipc_action_date               : logi [1:1365] NA ...
#>   ..$ ipc_section                   : chr [1:1365] "F" ...
#>   ..$ ipc_class                     : chr [1:1365] "02" ...
#>   ..$ ipc_subclass                  : chr [1:1365] "C" ...
#>   ..$ ipc_main_group                : chr [1:1365] "7" ...
#>   ..$ ipc_subgroup                  : chr [1:1365] "26" ...
#>   ..$ ipc_symbol_position           : logi [1:1365] NA ...
#>   ..$ ipc_classification_data_source: logi [1:1365] NA ...
#>   ..$ ipc_classification_value      : logi [1:1365] NA ...
#>  $ uspc_at_issue                      :'data.frame':	3806 obs. of  6 variables:
#>   ..$ patent_id        : chr [1:3806] "3930365" ...
#>   ..$ uspc_mainclass   : chr [1:3806] "60" ...
#>   ..$ uspc_mainclass_id: chr [1:3806] "60" ...
#>   ..$ uspc_subclass    : chr [1:3806] "60/391.4" ...
#>   ..$ uspc_subclass_id : chr [1:3806] "60/391.4" ...
#>   ..$ uspc_sequence    : int [1:3806] 0 1 ...
#>  $ wipo                               :'data.frame':	1305 obs. of  3 variables:
#>   ..$ patent_id    : chr [1:1305] "3930365" ...
#>   ..$ wipo_field_id: chr [1:1305] "27" ...
#>   ..$ wipo_sequence: int [1:1305] 0 0 ...
#>  $ us_term_of_grant                   :'data.frame':	21 obs. of  5 variables:
#>   ..$ patent_id      : chr [1:21] "3936555" ...
#>   ..$ term_grant     : logi [1:21] NA ...
#>   ..$ term_extension : logi [1:21] NA ...
#>   ..$ term_disclaimer: logi [1:21] NA ...
#>   ..$ disclaimer_date: chr [1:21] "1991-06-18" ...
#>  $ gov_interest_organizations         :'data.frame':	23 obs. of  5 variables:
#>   ..$ patent_id     : chr [1:23] "3936656" ...
#>   ..$ fedagency_name: chr [1:23] "Air Force" ...
#>   ..$ level_one     : chr [1:23] "Department of Defense" ...
#>   ..$ level_two     : chr [1:23] "Air Force" ...
#>   ..$ level_three   : chr [1:23] NA ...
#>  $ gov_interest_contract_award_numbers:'data.frame':	1 obs. of  2 variables:
#>   ..$ patent_id   : chr "3984680"
#>   ..$ award_number: chr "F19628-73-C-002"
#>  $ patents                            :'data.frame':	1000 obs. of  19 variables:
#>   ..$ patent_id                                                   : chr [1:10"..
#>   ..$ patent_title                                                : chr [1:10"..
#>   ..$ patent_type                                                 : chr [1:10"..
#>   ..$ patent_date                                                 : chr [1:10"..
#>   ..$ patent_year                                                 : int [1:100..
#>   ..$ patent_abstract                                             : chr [1:10"..
#>   ..$ patent_cpc_current_group_average_patent_processing_days     : int [1:100..
#>   ..$ patent_detail_desc_length                                   : int [1:100..
#>   ..$ patent_earliest_application_date                            : chr [1:10"..
#>   ..$ patent_num_foreign_documents_cited                          : int [1:100..
#>   ..$ patent_num_times_cited_by_us_patents                        : int [1:100..
#>   ..$ patent_num_total_documents_cited                            : int [1:100..
#>   ..$ patent_num_us_applications_cited                            : int [1:100..
#>   ..$ patent_num_us_patents_cited                                 : int [1:100..
#>   ..$ patent_processing_days                                      : int [1:100..
#>   ..$ patent_term_extension                                       : logi [1:10..
#>   ..$ gov_interest_statement                                      : chr [1:100..
#>   ..$ patent_uspc_current_mainclass_average_patent_processing_days: int [1:100..
#>   ..$ wipo_kind                                                   : chr [1:10"..
```

Now we are left with a series of flat data frames instead of having a single data frame with other data frames nested inside of it. These flat data frames can be joined together as needed via the primary key (`patent_id`).

[^1]: You can use `get_endpoints()` to list the endpoint names the R package uses.
[^2]: This webpage includes some details that are not relevant to the `query` argument in `search_pv`, such as the field list and sort parameter.
[^3]: You can unnest the data frames that are stored in the list columns using `unnest_pv_data()`. See the FAQs for details.
