---
title: "Result Set Paging"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Result Set Paging}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



  Paging changed in the new version of the Patentsview API.  This vignette tries to explain a
subtle gotcha that the R package handles for you and to show how to do your own paging.  Or
maybe it's trying to make the case for adding a max_rows parameter to search_pv()? :-)

  The R package lets you make a single request of up to 1000 rows or to retrieve all rows,
with nothing in between, unless you do your own paging.  This might be important if you
want to retrieve a few thousand utility patents without retrieving all 8 million of them.
Or maybe you want to iterate through search results page by page rather than retrieving
the entire data set and then iterating row by row.
If you do your own paging, you'll need to be careful when choosing your sort field, as
shown in Example 2.

## Example 1

**Note: A recent API release changed paging.**  We used to pass the unaltered last value we received.
Now we need to pad the patent_id to 8 characters in order to page through the whole result set.
This seems to be an intentional change, seeming only needed for patent_id, so ```pad_patent_id()```
was added to the R package.

Here we'll retrieve 5000 utility patents by paging.


``` r
library(patentsview)

# Lets get 5000 utility patents, 1000 at a time (the API's maximum rows per request)
requested_rows <- 1000
sort <- c("patent_id" = "asc")
query <- qry_funs$eq("patent_type" = "utility")
fields <- c("patent_id", "patent_date", "patent_title")

# The "after" parameter is explained a bit lower.  It's an Elasticsearch thing,
# which is the attrbute the new version of the API uses to page.  For now, just be 
# thankful that the R package handles this for you when you set all_pages = TRUE
after <- NULL
results <- list()

for (n in seq_len(5)) {
  after <- if(is.null(after)) after else pad_patent_id(after)
  print(paste("page", n, "after is", ifelse(is.null(after),"NULL",after)))

  page_n <- search_pv(query, fields = fields, sort = sort, 
    all_pages = FALSE, size = requested_rows, after = after)
   s <- names(sort)
   index <- nrow(page_n$data[[1]])
   after <- page_n$data[[1]][[s]][[index]]
   results[[n]] = page_n$data
}
#> [1] "page 1 after is NULL"
#> [1] "page 2 after is 03931271"
#> [1] "page 3 after is 03932272"
#> [1] "page 4 after is 03933272"
#> [1] "page 5 after is 03934274"

utility_patents <- as.data.frame(do.call(rbind, lapply(results, as.data.frame)))

str(utility_patents)
#> 'data.frame':	5000 obs. of  3 variables:
#>  $ patents.patent_id   : chr  "3930271" "3930272" "3930273" "3930274" ...
#>  $ patents.patent_title: chr  "Golf glove" "Crib leg lock" "Bed safety side rail arrangement" "Assembly for use in recreational activities" ...
#>  $ patents.patent_date : chr  "1976-01-06" "1976-01-06" "1976-01-06" "1976-01-06" ...
```
## Example 2

Here we will execute a query two different ways, the first having the R package do
the paging, the second will be our misguided attempt to do the paging ourselves.

As an exercise for the reader, the US patent office says there were 5677 patents 
[issued in January 1976](https://ppubs.uspto.gov/pubwebapp/external.html?q=@PD%3E=19760101%3C=19760131&db=USPAT&type=queryString)
while the patentsview database says there are 5352. Open as bug or try to figure out
why the numbers are so far off.

``` r

fields <- c("patent_id", "patent_date", "patent_title")
sort <- c("patent_date" = "asc")
query <- qry_funs$in_range(patent_date=c("1976-01-01", "1976-01-31"))
query
#> {"_and":[{"_gte":{"patent_date":"1976-01-01"}},{"_lte":{"patent_date":"1976-01-31"}}]}

r_pkg <- search_pv(query, sort = sort, fields = fields, all_pages = TRUE)

# note the number of rows returned
r_pkg$query_results$total_hits
#> [1] 5352
```

Now we'll try to do our own paging but as you might notice, we'll run into trouble.


``` r

after <- NULL
combined_data <- NULL
count <- 0
requested_rows <- 1000  # API's maximum rows per request

# We'll continue to make requests until we get back an empty or partial
# response from the API
page <- 1

repeat {
  print(paste("page", page, "after is", ifelse(is.null(after), "NULL", after)))

  subsequent <- search_pv(query, sort = sort, all_pages = FALSE,
    fields = fields, size = requested_rows, after = after)

  returned_rows <- subsequent$query_results$count
  count <- count + returned_rows 
  page <- page  + 1

  if(returned_rows > 0) {
     combined_data <- rbind(combined_data, subsequent$data$patents)
  }

  # We're done if we got an empty or partial reply from the API
  if(returned_rows < requested_rows) {
     break
  }

  # Now to page we need to set the "after" attribute to where the
  # current results ended.  Its value is the last row's [[sort field]]. 
  # It would need to be an array of values if there are multiple sort fields
  s <- names(sort)[[1]]
  after <- subsequent$data[[1]][[s]][[returned_rows]]

}
#> [1] "page 1 after is NULL"
#> [1] "page 2 after is 1976-01-06"
#> [1] "page 3 after is 1976-01-13"
#> [1] "page 4 after is 1976-01-20"
#> [1] "page 5 after is 1976-01-27"

print(paste("count is", count))
#> [1] "count is 4000"
print(nrow(combined_data))
#> [1] 4000
```

Here we ran into trouble since we chose patent_date as the sort field which
isn't unique in our result set as patent_id is in Example 1.  The R package
uses an appropriate primary key (```get_ok_pk(endpoint)```) when requesting
paged data (```all_pages = TRUE```) from an endpoint.  After all the pages
have been retrieved, the R package sorts the data as the user requested.
(This sorting methodology is inspired by the [Patentsview's python wrapper](https://github.com/PatentsView/PatentsView-APIWrapper)).
The lesson here is to pick a column with unique values to sort/page on, or, as in the
next example, use more than just a primary sort.

## Example 3

For completeness, this examples shows custom paging with a secondary sort field.
We'll use a small request size to to keep things simple


``` r

   query <- qry_funs$eq("patent_date" = "2007-01-02")

   # we'll apply a slightly nonsensical sort, something different than the API's default
   sort <- c("patent_date" = "desc", "patent_id" = "desc")
   size <- 10
   fields <- c("patent_id","patent_title","patent_date")
   full_data <- search_pv(query, sort = sort, size = size)

   # now we'll get the same data by making two paged requests
   size <- 5
   halves <- list()

   result <- search_pv(query, sort = sort, size = size, fields = fields)
   halves[[1]] <- result$data[[1]]

   # We need to let the API know where to resume data retrieval on our subsequent calls, 
   # after the values of our two sort keys, found in the last row of our result

   # quick check that there are more rows- that the first query didn't get them all
   if(result$query_results$count < result$query_results$total_hits)
   {
     last_row <- result$query_results$count

     after = list(
       result$data$patents[["patent_date"]][[last_row]],

       pad_patent_id(
         result$data$patents[["patent_id"]][[last_row]]
       )
     )

     result2 <- search_pv(query, sort = sort, size = size, after = after)
     halves[[2]] <- result2$data[[1]]
     combined <- do.call("rbind", c(halves, make.row.names = FALSE))
     testthat::expect_equal(combined, full_data$data[[1]])
     print(combined)
   }
#>    patent_id
#> 1    RE39458
#> 2    RE39457
#> 3    RE39456
#> 4    RE39455
#> 5    RE39454
#> 6    RE39453
#> 7    RE39452
#> 8    PP17341
#> 9    PP17340
#> 10   PP17339
#>                                                                patent_title
#> 1                                 Remote file transfer method and apparatus
#> 2                  Liquid specimen container and attachable testing modules
#> 3                                       Radioactive embolizing compositions
#> 4               Video coding method and decoding method and devices thereof
#> 5                              Transfer of messages in a multiplexed system
#> 6                                           Low profile inductive component
#> 7  TFT substrate with low contact resistance and damage resistant terminals
#> 8                                             Papaver plant named ‘Firefly’
#> 9                                           Diascia plant named ‘Balwinorg’
#> 10                                       Delphinium plant named ‘Barthirty’
#>    patent_date
#> 1   2007-01-02
#> 2   2007-01-02
#> 3   2007-01-02
#> 4   2007-01-02
#> 5   2007-01-02
#> 6   2007-01-02
#> 7   2007-01-02
#> 8   2007-01-02
#> 9   2007-01-02
#> 10  2007-01-02
```


## Reader Exercise

Ok, I'll get you started on the user exercise. Trivia: with a handful of exceptions,
patents were issued on Tuesdays.


``` r
   uspto_counts <- c(1478, 1312, 1449, 1438)

   issue_date <- as.Date("1976-01-06")  # first Tuesday of January 1976

   weekly_counts <- lapply(seq(from = 0, to = 21, by = 7), function(additional_days, base_issue_date) {
     issue_date <- base_issue_date + additional_days
     query <- qry_funs$eq("patent_date" = as.character(issue_date))
     query
     issued_patents <- search_pv(query)
     print(paste("issue date", issue_date, issued_patents$query_results$total_hits, 
        "issued patents"))
     issued_patents$query_results$total_hits
   }, issue_date)
#> [1] "issue date 1976-01-06 1379 issued patents"
#> [1] "issue date 1976-01-13 1257 issued patents"
#> [1] "issue date 1976-01-20 1383 issued patents"
#> [1] "issue date 1976-01-27 1332 issued patents"

   total <- do.call(sum, weekly_counts)
   print(paste("patentsview total", total))
#> [1] "patentsview total 5351"
   print(paste("uspto total", sum(uspto_counts)))
#> [1] "uspto total 5677"
```


Ok, I couldn't resist, I feel an API bug report submission coming on.  It look like there
are reissued patents in our range, but there aren't design patents.
Here's a USPTO [search](https://ppubs.uspto.gov/pubwebapp/external.html?q=@PD>=19760106<=19760127%20and%20(D23$).pn.&db=USPAT&type=queryString) 
that shows the design patents issued in January 1976.


<a name="missing">As this shows, there aren't design patents in the patentsview database until 1976-12-07 and plant patents don't appear until 1976-12-14.


``` r
  fields <- c("patent_id","patent_title","patent_date","patent_type")
  sort <- c("patent_date" = "asc")

  result <- search_pv(qry_funs$eq("patent_type" = "design"), size = 1, sort = sort, fields = fields)
  print(result$data)
#> #### A list with a single data frame on patents level:
#> 
#> List of 1
#>  $ patents:'data.frame':	1 obs. of  4 variables:
#>   ..$ patent_id   : chr "D242583"
#>   ..$ patent_title: chr "Sports shoe"
#>   ..$ patent_type : chr "design"
#>   ..$ patent_date : chr "1976-12-07"

  result <- search_pv(qry_funs$eq("patent_type" = "plant"), size = 1, sort = sort, fields = fields)
  print(result$data)
#> #### A list with a single data frame on patents level:
#> 
#> List of 1
#>  $ patents:'data.frame':	1 obs. of  4 variables:
#>   ..$ patent_id   : chr "PP3987"
#>   ..$ patent_title: chr "Strawberry plant"
#>   ..$ patent_type : chr "plant"
#>   ..$ patent_date : chr "1976-12-14"
```


``` r
   uspto_design_counts <- c(88, 54, 63, 103)

   issue_date <- as.Date("1976-01-06")  # first Tuesday of January 1976

   weekly_counts <- lapply(seq(from = 0, to = 21, by = 7), function(additional_days, base_issue_date) {
     issue_date <- base_issue_date + additional_days
     query <- with_qfuns(
       and(
         eq("patent_date" = as.character(issue_date)),
         eq("patent_type" = "design")
        )
      )

     design_patents <- search_pv(query)
     print(paste("issue date", issue_date, design_patents$query_results$total_hits, 
        "design patents"))
     design_patents$query_results$total_hits
   }, issue_date)
#> [1] "issue date 1976-01-06 0 design patents"
#> [1] "issue date 1976-01-13 0 design patents"
#> [1] "issue date 1976-01-20 0 design patents"
#> [1] "issue date 1976-01-27 0 design patents"

   total <- do.call(sum, weekly_counts)
   print(paste("patentsview total", total))
#> [1] "patentsview total 0"
   print(paste("uspto design total", sum(uspto_design_counts)))
#> [1] "uspto design total 308"
```

There is still a small discrepancy if you need something to look into.  (uspto total - patentsview total = 325 patents.
308 are the missing design patents but where did the other 17 go?)  Slight hint if you want it,
there were 4 [plant patents](https://ppubs.uspto.gov/pubwebapp/external.html?q=@PD>=19760106<=19760127%20and%20(D23$).pn.&db=USPAT&type=queryString) 
issued in January 1976, but that leaves 10 to still find...





