---
title: "Top assignees"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Top assignees}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



> Note about the affect of the api change
>
> This would be a good example of life under the new api, where we have to make more than one call to get the same data as before.  Maybe even keep the old page around for comparison? If only I could manipulate dataframes!
>
> Intention (partially implemented): 
> application date or year isn't available from any of the new version of the api's endpoints.  Instead we'll use patent_year (the year the patent was granted, already of type integer).  Trouble is that it's at the patent level, not inside the nested assignees_at_grant.  Lacking the skill to get it there.
>
> Remove the hacked Total number of patents and add assignee_id to the top_asgns data frame, make a call to the assignee endpoint to get num_patents (total number of patents) for the top 75 assignees, then if it's not too unRish, remove the assignee_id column and add the total number of patents column and calculate the percentage (or create a new data frame with the columns we want in the datatable).  Then life, and the script, goes on as normal (as the old one did). 


The following is a quick analysis of the top organizations patenting in the field of databases.

1. The first step is to download the relevant data fields from the PatentsView API:


```r
library(patentsview)
library(dplyr)
library(highcharter)
library(DT)
library(knitr)
library(stringr)

# With the recent api change that limits the overall result set size, we now look
# for databases (plural) where we used to use the singular database for this example.
# We also exclude patents without an assignee organization.

# We first need to write a query. Our query will look for "databases" in either 
# the patent title or abstract...Note, this isn't a terribly good way to ID our 
# patents, but it will work for the purpose of demonstration. Users who are 
# interested in writing higher-quality queries could consult the large body of 
# research that has been done in field of patent document retrieval.
query <- with_qfuns(
  and(
     neq("assignees_at_grant.organization" = ""),
     or(
       text_phrase(patent_abstract = "databases"),
       contains(patent_title = "databases")
     )
   )
)

query
#> {"_and":[{"_neq":{"assignees_at_grant.organization":""}},{"_or":[{"_text_phrase":{"patent_abstract":"databases"}},{"_contains":{"patent_title":"databases"}}]}]}

# Create a list of the fields we'll need for the analysis
# using assignee's type since we can't get assignee_total_num_patents from 
# the patent endpoint

fields <- c(
  "patent_number", "patent_date","patent_year",
  "assignees_at_grant.type",  # hack since we don't get the total number of patents by assignee from the endpoint now
  "assignees_at_grant.organization",  # full text field now if used in q:
  "assignees_at_grant.assignee_id"  # this comes back as "assignees_at_grant.assignee
)

# Send an HTTP request to the PatentsView API to get the data
pv_out <- search_pv(query, fields = fields, all_pages = TRUE)
#> [1] "https://search.patentsview.org/api/v1/patent/?q=%7B%22_and%22%3A%5B%7B%22_neq%22%3A%7B%22assignees_at_grant.organization%22%3A%22%22%7D%7D%2C%7B%22_or%22%3A%5B%7B%22_text_phrase%22%3A%7B%22patent_abstract%22%3A%22databases%22%7D%7D%2C%7B%22_contains%22%3A%7B%22patent_title%22%3A%22databases%22%7D%7D%5D%7D%5D%7D&f=[\"patent_number\",\"patent_date\",\"patent_year\",\"assignees_at_grant.type\",\"assignees_at_grant.organization\",\"assignees_at_grant.assignee_id\"]&o={\"offset\":0,\"size\":1000}&s="
#> [1] "https://search.patentsview.org/api/v1/patent/?q=%7B%22_and%22%3A%5B%7B%22_neq%22%3A%7B%22assignees_at_grant.organization%22%3A%22%22%7D%7D%2C%7B%22_or%22%3A%5B%7B%22_text_phrase%22%3A%7B%22patent_abstract%22%3A%22databases%22%7D%7D%2C%7B%22_contains%22%3A%7B%22patent_title%22%3A%22databases%22%7D%7D%5D%7D%5D%7D&f=[\"patent_number\",\"patent_date\",\"patent_year\",\"assignees_at_grant.type\",\"assignees_at_grant.organization\",\"assignees_at_grant.assignee_id\"]&o={\"offset\":0,\"size\":1000}&s="
#> [1] "https://search.patentsview.org/api/v1/patent/?q=%7B%22_and%22%3A%5B%7B%22_neq%22%3A%7B%22assignees_at_grant.organization%22%3A%22%22%7D%7D%2C%7B%22_or%22%3A%5B%7B%22_text_phrase%22%3A%7B%22patent_abstract%22%3A%22databases%22%7D%7D%2C%7B%22_contains%22%3A%7B%22patent_title%22%3A%22databases%22%7D%7D%5D%7D%5D%7D&f=[\"patent_number\",\"patent_date\",\"patent_year\",\"assignees_at_grant.type\",\"assignees_at_grant.organization\",\"assignees_at_grant.assignee_id\"]&o={\"offset\":1000,\"size\":1000}&s="
#> [1] "https://search.patentsview.org/api/v1/patent/?q=%7B%22_and%22%3A%5B%7B%22_neq%22%3A%7B%22assignees_at_grant.organization%22%3A%22%22%7D%7D%2C%7B%22_or%22%3A%5B%7B%22_text_phrase%22%3A%7B%22patent_abstract%22%3A%22databases%22%7D%7D%2C%7B%22_contains%22%3A%7B%22patent_title%22%3A%22databases%22%7D%7D%5D%7D%5D%7D&f=[\"patent_number\",\"patent_date\",\"patent_year\",\"assignees_at_grant.type\",\"assignees_at_grant.organization\",\"assignees_at_grant.assignee_id\"]&o={\"offset\":2000,\"size\":1000}&s="
#> [1] "https://search.patentsview.org/api/v1/patent/?q=%7B%22_and%22%3A%5B%7B%22_neq%22%3A%7B%22assignees_at_grant.organization%22%3A%22%22%7D%7D%2C%7B%22_or%22%3A%5B%7B%22_text_phrase%22%3A%7B%22patent_abstract%22%3A%22databases%22%7D%7D%2C%7B%22_contains%22%3A%7B%22patent_title%22%3A%22databases%22%7D%7D%5D%7D%5D%7D&f=[\"patent_number\",\"patent_date\",\"patent_year\",\"assignees_at_grant.type\",\"assignees_at_grant.organization\",\"assignees_at_grant.assignee_id\"]&o={\"offset\":3000,\"size\":1000}&s="
#> [1] "https://search.patentsview.org/api/v1/patent/?q=%7B%22_and%22%3A%5B%7B%22_neq%22%3A%7B%22assignees_at_grant.organization%22%3A%22%22%7D%7D%2C%7B%22_or%22%3A%5B%7B%22_text_phrase%22%3A%7B%22patent_abstract%22%3A%22databases%22%7D%7D%2C%7B%22_contains%22%3A%7B%22patent_title%22%3A%22databases%22%7D%7D%5D%7D%5D%7D&f=[\"patent_number\",\"patent_date\",\"patent_year\",\"assignees_at_grant.type\",\"assignees_at_grant.organization\",\"assignees_at_grant.assignee_id\"]&o={\"offset\":4000,\"size\":1000}&s="
#> [1] "https://search.patentsview.org/api/v1/patent/?q=%7B%22_and%22%3A%5B%7B%22_neq%22%3A%7B%22assignees_at_grant.organization%22%3A%22%22%7D%7D%2C%7B%22_or%22%3A%5B%7B%22_text_phrase%22%3A%7B%22patent_abstract%22%3A%22databases%22%7D%7D%2C%7B%22_contains%22%3A%7B%22patent_title%22%3A%22databases%22%7D%7D%5D%7D%5D%7D&f=[\"patent_number\",\"patent_date\",\"patent_year\",\"assignees_at_grant.type\",\"assignees_at_grant.organization\",\"assignees_at_grant.assignee_id\"]&o={\"offset\":5000,\"size\":1000}&s="
#> [1] "https://search.patentsview.org/api/v1/patent/?q=%7B%22_and%22%3A%5B%7B%22_neq%22%3A%7B%22assignees_at_grant.organization%22%3A%22%22%7D%7D%2C%7B%22_or%22%3A%5B%7B%22_text_phrase%22%3A%7B%22patent_abstract%22%3A%22databases%22%7D%7D%2C%7B%22_contains%22%3A%7B%22patent_title%22%3A%22databases%22%7D%7D%5D%7D%5D%7D&f=[\"patent_number\",\"patent_date\",\"patent_year\",\"assignees_at_grant.type\",\"assignees_at_grant.organization\",\"assignees_at_grant.assignee_id\"]&o={\"offset\":6000,\"size\":1000}&s="
#> [1] "https://search.patentsview.org/api/v1/patent/?q=%7B%22_and%22%3A%5B%7B%22_neq%22%3A%7B%22assignees_at_grant.organization%22%3A%22%22%7D%7D%2C%7B%22_or%22%3A%5B%7B%22_text_phrase%22%3A%7B%22patent_abstract%22%3A%22databases%22%7D%7D%2C%7B%22_contains%22%3A%7B%22patent_title%22%3A%22databases%22%7D%7D%5D%7D%5D%7D&f=[\"patent_number\",\"patent_date\",\"patent_year\",\"assignees_at_grant.type\",\"assignees_at_grant.organization\",\"assignees_at_grant.assignee_id\"]&o={\"offset\":7000,\"size\":1000}&s="
```

2. Now let's identify who the top assignees are based on how many patents they have in our data set. We'll also calculate how many total patents these assignees have and what fraction of their total patents relate to databases.


```r
# Unnest the data frames that are stored in the assignee list column
dl <- unnest_pv_data(pv_out$data, "patent_number")
dl
#> List of 2
#>  $ assignees_at_grant:'data.frame':	7150 obs. of  4 variables:
#>   ..$ patent_number: chr [1:7150] "4751635" ...
#>   ..$ assignee     : chr [1:7150] "https://search.patentsview.org/api/v1/assi"..
#>   ..$ type         : chr [1:7150] "2" ...
#>   ..$ organization : chr [1:7150] "Bell Communications Research, Inc." ...
#>  $ patents           :'data.frame':	7598 obs. of  3 variables:
#>   ..$ patent_number: chr [1:7598] "4751635" ...
#>   ..$ patent_date  : chr [1:7598] "1988-06-14" ...
#>   ..$ patent_year  : int [1:7598] 1988 1988 ...

# we shouldn't need the filter (we queried for non empty string orginazations) but
# some are NA somehow

# we don't get the assignee_total_num_patents back from the patents endpoint
# can we calculate it ourselves? using the assignees_at_grant type for the code to work (HACK)

# get the assignee_ids for the top 75 assignees - we'll call the assignee endpoint with them
# to get the total number of patents

# requested assignees_at_grant.assignee_id comes back in the assignees_at_grant object 
# with key "assignee" and value of https://search.patentsview.org/api/v1/assignee/35/
# we want to parse out the assignee_ids (35 in the example value)
# str_extract(assignee, "(\\d+)(?=/$)")

# would really not want ttl_pats and division yet but we'll leave it for now

# Create a data frame with the top 75 assignees:
top_asgns <-
  dl$assignees_at_grant %>%
    filter(!is.na(organization)) %>% # some patents are assigned to an inventor (not an org)
    mutate(ttl_pats = as.numeric(type)) %>%
    mutate(assignee_id = str_extract(assignee, "(\\d+)(?=/$)")) %>%
    group_by(organization, ttl_pats, assignee_id) %>% 
    summarise(db_pats = n()) %>% 
    mutate(frac_db_pats = round(db_pats / ttl_pats, 3)) %>%
    ungroup() %>%
    select(c(1, 4, 2, 5, 3)) %>%
    arrange(desc(db_pats)) %>%
    slice(1:75)

# now that we have the assignee_id's we can call the assignee endpoint to get the
# total number of patents for each of our top_asgns 

# in this case it might be nice to have a qry_funs$in for the api's array eq
# thinking the api might not like 75 or'ed conditions (thought it did work when I tried it)
#assignee_query =  qry_funs$eq(assignee_id = as.integer(top_asgns$assignee_id))
s = toString(as.integer(top_asgns$assignee_id))
assignee_query = paste('{"assignee_id":[',s,']}')

assignee_fields <- c(
  "assignee_id","organization", "num_patents" 
)

# we'll post to the api, the query is pretty large if we use qry_funs$eq
assignee_out <- search_pv(assignee_query , fields = assignee_fields, all_pages = TRUE, 
   endpoint = "assignee", method = "POST")

# TODO:
# now we'd want to mutate in the total counts and do the percentage math in top_asgns 
# some type of join exceeding my capabilities!

# remove assignee_id column
top_asgns <-  top_asgns  %>% select (-c(assignee_id))

# Create datatable
datatable(
  data = top_asgns,
  rownames = FALSE,
  colnames = c(
    "Assignee", "DB patents","Total patents", "DB patents / total patents"
  ),
  caption = htmltools::tags$caption(
    style = 'caption-side: top; text-align: left; font-style: italic;',
    "Table 1: Top assignees in 'databases'"
  ),
  options = list(pageLength = 10)
)
#> Error in loadNamespace(name): there is no package called 'webshot'
```

<br>

IBM is far and away the biggest player in the field. However, we can see that Oracle and Salesforce.com are relatively more interested in this area, as indicated by the fraction of their patents that relate to databases.

3. Let's see how these assignees' level of investment in databases has changed over time.


```r

# The patent endpoint no longer returns application date as this page used originally
# Instead we will use the patent_year
# Alarmingly the application date is not available from any endpoint!

# don't know enough R to do this properly!
# would really only want to return the patent year if the 

with_grant_years = lapply(pv_out$data$patents, function(y,i) {
   grant_year = y$patent_year
   abc = c()
   lapply(y$assignees_at_grant, function(z,i) {
      abc = append(abc, grant_year)
      z
      }, y$assignees_at_grant)
   y$assignees_at_grant$grant_year = abc
   y
}, y=pv_out$data$patents)


# trouble is that this is the years for all assignees, not just the top 75
# probably need to iterate through top_asgns to figure this out or to 
# have something we can join to below

# wanting to add grant_year to assignees_at_grant but it's failing
##pv_out$data$patents$assignees_at_grant$grant_year <- NA
##pv_out$data$patents$assignees_at_grant$grant_year <- grant_years$patent_year
# replacement has 6599 rows, data has 6598

# Create a data frame with patent counts by grant year for each assignee

data <- 
  top_asgns %>%
    select(-contains("pats")) %>%
    slice(1:5) %>%
    inner_join(dl$assignees_at_grant) %>%
   # inner_join(dl$applications) %>%
   mutate(grant_yr = dl$assignees_at_grant$grant_year) %>%
   group_by(dl$assignees_at_grant.organization, grant_yr) %>%
   count() 
#> Error: Problem adding computed columns in `group_by()`.
#> x Problem with `mutate()` input `..2`.
#> i `..2 = grant_yr`.
#> x object 'grant_yr' not found



# Plot the data using highchartr:
hchart(
  data, "line", 
  hcaes(x = grant_yr, y = n, group = assignee_organization)
) %>%
  hc_plotOptions(series = list(marker = list(enabled = FALSE))) %>%
  hc_xAxis(title = list(text = "Grant year")) %>%
  hc_yAxis(title = list(text = "Patents")) %>%
  hc_title(text = "Top five assignees in 'databases'") %>%
  hc_subtitle(text = "Yearly granted patents over time")
#> Error: Objects of class/type function are not supported by hchart (yet).
```

It's hard to see any clear trends in this graph. What is clear is that the top assignees have all been patenting in the field for many years.

4. Finally, let's see how the organizations compare in terms of their citation rates. First, we'll need to normalize the raw citation counts by publication year, so that older patents don't have an unfair advantage over younger patents (i.e., because they have had a longer time to accumulate citations).


```r
# Write a ranking function that will be used to rank patents by their citation counts
percent_rank2 <- function(x)
  (rank(x, ties.method = "average", na.last = "keep") - 1) / (sum(!is.na(x)) - 1)

# Create a data frame with normalized citation rates and stats from Step 2
asng_p_dat <-
  dl$patents %>%
    mutate(patent_yr = substr(patent_date, 1, 4)) %>%
    group_by(patent_yr) %>%
    mutate(perc_cite = percent_rank2(patent_num_cited_by_us_patents)) %>%
    inner_join(dl$assignees) %>%
    group_by(assignee_organization) %>%
    summarise(mean_perc = mean(perc_cite)) %>%
    inner_join(top_asgns) %>%
    arrange(desc(ttl_pats)) %>%
    filter(!is.na(assignee_organization)) %>%
    slice(1:20) %>%
    mutate(color = "#f1c40f") %>%
    as.data.frame()
#> Error: Problem with `mutate()` column `perc_cite`.
#> i `perc_cite = percent_rank2(patent_num_cited_by_us_patents)`.
#> x object 'patent_num_cited_by_us_patents' not found
#> i The error occurred in group 1: patent_yr = "1987".

kable(head(asng_p_dat), row.names = FALSE)
#> Error in head(asng_p_dat): object 'asng_p_dat' not found
```

Now let's visualize the data. Each assignee will be represented by a point/bubble. The x-value of the point will represent the total number of patents the assignee has published in the field of databases (on a log scale), while the y-value will represent its average normalized citation rate. The size of the bubble will be proportional to the percent of the assignee's patents that relate to databases.


```r
# Adapted from http://jkunst.com/highcharter/showcase.html
hchart(
  asng_p_dat, "scatter", 
  hcaes(x = db_pats, y = mean_perc, size = frac_db_pats, 
        group = assignee_organization, color = color)
) %>%
  hc_xAxis(
    title = list(text = "DB patents"), type = "logarithmic",
    allowDecimals = FALSE, endOnTick = TRUE
  ) %>%
  hc_yAxis(title = list(text = "Mean cite perc.")) %>%
  hc_title(text = "Top assignees in 'databases'") %>%
  hc_add_theme(hc_theme_flatdark()) %>%
  hc_tooltip(
    useHTML = TRUE, pointFormat = tooltip_table(
    x = c("DB patents", "Mean cite percentile", "Fraction DB patents"),
    y = c("{point.db_pats:.0f}","{point.mean_perc:.2f}", "{point.frac_db_pats:.3f}")
  )) %>%
  hc_legend(enabled = FALSE)
#> Error in hchart(asng_p_dat, "scatter", hcaes(x = db_pats, y = mean_perc, : object 'asng_p_dat' not found
```

<br>

It looks like Microsoft has relatively high values across all three three metrics (average citation percentile, number of database patents, and percent of total patents that are related to databases). IBM has more patents than Microsoft, but also has a lower average citation percentile.
